### PR TITLE
fixing terrain sliding; converting shader to RawShaderMaterial

### PR DESCRIPTION
**Pull request by Sekuta82**

### CODE REVIEW

**Comment by Sekuta82** [comment]
@thefoofighter Take it!!! Do it!!! Hit that merge button : )

**Comment by thefoofighter** [comment]
@Sekuta82 Raw shader should be fine. but what is the terrain sliding?

**Comment by Sekuta82** [comment]
This offset caused the objects to move on the surface when they should be stuck to the ground.




On Mon, Dec 23, 2019 at 2:34 PM +0100, "Cathal McNally" <notifications@github.com> wrote:












@Sekuta82 Raw shader should be fine. but what is the terrain sliding?

**Comment by thefoofighter** [comment]
hehe, Sorry man, I got confused I thought you were asking me to fix these issues :P Realize now it was just a merge request :D 

It was a late night : P

**Comment by Sekuta82** [comment]
Don't worry, I don't want you to clean up my mess :D




On Mon, Dec 23, 2019 at 4:42 PM +0100, "Cathal McNally" <notifications@github.com> wrote:












hehe, Sorry man, I got confused I thought you were asking me to fix these issues :P Realize now it was just a merge request :D


It was a late night : P

**Pull request merged**
